stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1.$CI_PIPELINE_ID%{?dist}/g" mech_eap.spec.in
    - sed -i "s/\(.\)%{?dist}/\1.$CI_PIPELINE_ID%{?dist}/g" moonshot.spec.in
    - "for i in ui libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2F$i/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - yum -y install RPMS/x86_64/*.rpm
    - rm -fr RPMS SRPMS deps.zip
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv mech_eap*.tar.gz SOURCES
    - rpmbuild -ba mech_eap.spec --define "_topdir `pwd`"
    - rpmbuild -ba moonshot.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
      - RPMS
      - SRPMS

.centoscommon-noshib: &centoscommon-noshib
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1.$CI_PIPELINE_ID%{?dist}/g" mech_eap_noshib.spec.in
    - sed -i "s/\(.\)%{?dist}/\1.$CI_PIPELINE_ID%{?dist}/g" moonshot_noshib.spec.in
    - "for i in ui libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2F$i/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - yum -y install RPMS/x86_64/*.rpm
    - rm -fr RPMS SRPMS deps.zip
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir SOURCES
    - mv mech_eap*.tar.gz SOURCES
    - rpmbuild -ba mech_eap_noshib.spec --define "_topdir `pwd`"
    - rpmbuild -ba moonshot_noshib.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
      - RPMS
      - SRPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - "for i in ui libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2F$i/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.debiancommon-noshib: &debiancommon-noshib
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - "for i in ui libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2F$i/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - "dpkg -i build/*.deb || true"
    - apt-get install -fy
    - rm -fr build deps.zip
    - cp debian/control_noshib debian/control
    - cp debian/rules_noshib debian/rules
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - cp $APKBUILD APKBUILD.in
    - "for i in ui libradsec; do wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2F$i/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip; done"
    - apk add apks/*/*.apk --allow-untrusted
    - rm -fr apks deps.zip
    - sed -i "s/pkgrel=0/pkgrel=$CI_PIPELINE_ID/g" APKBUILD.in
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/moonshot/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos6:
  image: $DOCKER_REGISTRY_URL/centos6:latest
  <<: *centoscommon

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian8:
  image: $DOCKER_REGISTRY_URL/debian8:latest
  <<: *debiancommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian8:
  image: $DOCKER_REGISTRY_URL/raspbian8:latest
  when: manual
  <<: *debiancommon

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  when: manual
  <<: *debiancommon

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  when: manual
  <<: *debiancommon

ubuntu16:
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon

centos6-noshib:
  variables:
    CI_JOB_NAME: centos6
  image: $DOCKER_REGISTRY_URL/centos6:latest
  <<: *centoscommon-noshib

centos7-noshib:
  variables:
    CI_JOB_NAME: centos7
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon-noshib

centos8-noshib:
  variables:
    CI_JOB_NAME: centos8
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon-noshib

debian8-noshib:
  variables:
    CI_JOB_NAME: debian8
  image: $DOCKER_REGISTRY_URL/debian8:latest
  <<: *debiancommon-noshib

debian9-noshib:
  variables:
    CI_JOB_NAME: debian9
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon-noshib

debian10-noshib:
  variables:
    CI_JOB_NAME: debian10
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon-noshib

raspbian8-noshib:
  variables:
    CI_JOB_NAME: raspbian8
  image: $DOCKER_REGISTRY_URL/raspbian8:latest
  when: manual
  <<: *debiancommon-noshib

raspbian9-noshib:
  variables:
    CI_JOB_NAME: raspbian9
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  when: manual
  <<: *debiancommon-noshib

raspbian10-noshib:
  variables:
    CI_JOB_NAME: raspbian10
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  when: manual
  <<: *debiancommon-noshib

ubuntu16-noshib:
  variables:
    CI_JOB_NAME: ubuntu16
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon-noshib

ubuntu18-noshib:
  variables:
    CI_JOB_NAME: ubuntu18
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon-noshib

alpine38:
  image: $DOCKER_REGISTRY_URL/alpine38:latest
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine38_armhf:
  image: $DOCKER_REGISTRY_URL/alpine38_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine39:
  image: $DOCKER_REGISTRY_URL/alpine39:latest
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon

alpine39_armhf:
  image: $DOCKER_REGISTRY_URL/alpine39_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon

alpine311:
  image: $DOCKER_REGISTRY_URL/alpine311:latest
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon

alpine311_armhf:
  image: $DOCKER_REGISTRY_URL/alpine311_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon
